#!/bin/bash

./makemain

echo "Making Appendix 1"
echo -ne '\n' | pdflatex appendix1
bibtex appendix1
echo -ne '\n' | pdflatex appendix1
echo -ne '\n' | pdflatex appendix1

echo "Making Appendix 3"
echo -ne '\n' | pdflatex appendix3
bibtex appendix3
echo -ne '\n' | pdflatex appendix3
echo -ne '\n' | pdflatex appendix3

echo "Making Appendix 4"
echo -ne '\n' | pdflatex appendix4

echo "Making Appendix 5"
echo -ne '\n' | pdflatex appendix5

echo "Merging PDF"
python merge.py
echo "Cleaning Files"
./cleanfiles